name: 'DCM Action'
description: 'Run DCM checks'
author: 'dcm.dev'

branding:
  color: 'blue'
  icon: 'search'

inputs:
  github_token:
    description: 'Token to connect to GitHub. Use secrets.GITHUB_TOKEN.'
    required: true
  github_pat:
    description: 'Personal access token. Required if you have private GitHub repository in the package dependencies.'
    required: false
  ci_key:
    description: 'License key to run on CI server.'
    required: true
  email:
    description: 'Email used to purchase the license.'
    required: true
  folders:
    description: 'List of folders and files (separated by commas) to scan.'
    required: false
    default: 'lib'
  pull_request_comment:
    description: 'Publish report overview directly into your pull request.'
    required: false
    default: 'true'
  pull_request_comment_on_fail:
    description: 'Publish report overview directly into your pull request only when DCM checks fail.'
    required: false
    default: 'false'
  package_name:
    description: 'Package name to differentiate the report. Set when running several DCM runs at once.'
    required: false
  fatal_warnings:
    description: 'Treat warning level issues as fatal.'
    required: false
    default: 'true'
  fatal_performance:
    description: 'Treat performance level issues as fatal.'
    required: false
    default: 'true'
  fatal_style:
    description: 'Treat style level issues as fatal.'
    required: false
    default: 'true'

runs:
  using: 'node16'
  main: 'dist/index.js'
